### ISSUE TITLE
feat(data-modeling): create Product.SecondHand component and link to Product.Item

### ISSUE THREAD

**Issue by jtfairbank** [distributeaid/aggregated-public-information#13]
Create `Product.SecondHand` component with fields based on the `Product Info` spreadsheet:

- can be used - boolean
- price adjustment - numeric (percent, 0 - 100)

Issue goals:

- [ ] Create `Product.SecondHand` component
- [ ] Link `Product.PriceAdjustment` component to the product.item collection
- Note: there should only be 1 `Product.SecondHand` component for each `Product.Item`

**Comment by TravisAlmey** [comment]
nitpick(non-blocking): ideally we should have a way to disable the `priceAdjustment` field when the `canBeUsed` field is set to false as that value won't be meaningful if the item can't be used, but it's not a big deal if we can't disable that.
