### ISSUE TITLE
Feat(data modeling): Create Product.Volume component and link to Product.Item collection type

### ISSUE THREAD

**Issue by ll-zerr** [distributeaid/aggregated-public-information#16]
Create Product.Volume component with fields based on the product info table.

These fields include:

- Package volume (numeric)
- Volume unit (text)
- Count per package (numeric)
- Item volume (numeric)
- Count per CBM (numeric)
- Volume source (text, url)
- Log date (date)
- Notes (text)

Issue goals:

- [x]  Create Product.Volume component
- [x]  Link Product.Volume component to the Product.Item collection
- [x]  Support linking multiple Product.Volumes to a Product.Item

**Comment by jtfairbank** [comment]
@ll-zerr  looking good! A few suggestions using [conventional comments](https://conventionalcomments.org/):

- suggestion(blocking): make the volume unit some sort of select field with preset options. fine to update the issue after you start working on a branch and can explore what fields Strapi has to offer. you can see the options we have in the spreadsheet
- note: item volume and count per cbm are calculated fields. we can make them manually enter-able for now to get the model right, but down the road we'll want to hide them from the Strapi content entry form and instead calculate them when we create / update an item.
    - to calculate item volume: normalize the package volume to cbm, then divide by the count/package
    - to calculate count per cbm: inverse the item volume (ie 1 / item_volume)

Feel free to get started coding! You can always adjust your issue as you go!
