### ISSUE TITLE
Feat(data modeling): Create Product.PackSize component and link to Product.Item collection type

### ISSUE THREAD

**Issue by ll-zerr** [distributeaid/aggregated-public-information#26]
Create Product.PackSize component with a numeric field based on the Product Info Spreadsheet.

Issue Goals:
- [ ]  Create Product.PackSize component
- [ ]  Link Product.PackSize component to the Product.Item collection
- [ ]  Support multiple Product.PackSizes to a Product.Item

**Comment by jtfairbank** [comment]
Hey @ll-zerr thanks so much for catching this!  Since it's just a single data field, I'm going to implement it as a field directly on `Product.Item` for now.
