### ISSUE TITLE
Feat(data modeling): Create Financial.CurrencyConversion collection type

### ISSUE THREAD

**Issue by ll-zerr** [distributeaid/aggregated-public-information#32]
Create Financial.CurrencyConversion collection with the following fields (sourced from the Financial Conversions doc):

- year (numeric)
- month (numeric)
- currency (enumeration)
- equivalentToUSD (numeric)
- source (text, url)
- notes (text)

Issue Goals:

- [✔️ ] Create Financial.CurrencyConversion collection

**Comment by jtfairbank** [comment]
Hey @ll-zerr looks great!  I'd probably change the name to `Financial.CurrencyConversion`, the monthly nature of it will just be a property of the type.  For `One USD equals` we should probably name that something like `equivalentToUSD` or something since you can't have spaces in the type name.

**Comment by ll-zerr** [comment]
Note: Needed to create the year field type as short text to avoid a comma in the value.
