### ISSUE TITLE
Feat(data modeling): Create Financial.GDPConversions collection type

### ISSUE THREAD

**Issue by ll-zerr** [distributeaid/aggregated-public-information#41]
Create Financial.GDPConversions collection with the following fields (sourced from the Financial Conversions doc):

- Country (enumeration)    **Note**: May be able to use the **country select plugin** here
- Year (numeric)
- GDPPerCapita_PPP_InternationalDollar (numeric)
- Source (text, url)
- Last updated (date)
- Ratio US to Country (number, percentage)
- Country code (enumeration)
- Currency (enumeration)
- Notes (text)

Issue Goals:

- [ ] - Create Financial.GDPConversions collection
- [ ] - Confirm field types for Country, Country code and currency

**Comment by swizzard** [comment]
@ll-zerr and/or @thegrumpyenby if the **country select plugin** doesn't seem to be available, is there a list of countries and codes I can use? I took currencies from [here](https://github.com/distributeaid/aggregated-public-information/blob/saga/src/api/financial/content-types/currency-conversion/schema.json#L25), let me know if there's some other list I should use instead.

**Comment by thegrumpyenby** [comment]
@swizzard I’m of zero help here, unfortunately 😆 but if Laura doesn’t see this you can always @ her on Slack as well!

**Comment by ll-zerr** [comment]
@swizzard I just sent the google doc to you in Slack that I was referencing when creating this issue. It holds the data for this collection.
