### ISSUE TITLE
Feat(data modeling): Create NeedsAssessment.Need collection type

### ISSUE THREAD

**Issue by ll-zerr** [distributeaid/aggregated-public-information#44]
Create NeedsAssessment.Need collection with the following fields (sourced from the [post-processing data models for Needs Assessments from the Gatsby site](https://github.com/distributeaid/distributeaid.org/blob/saga/gatsby/needs-assessment/sourceNeedsAssessmentData.ts):

- id (uid)
- survey (see Notes below)
- place (relation)
- product (relation)
- need (number)

Issue Goals:

- [ ✔️] Create NeedsAssessment.Need collection
- [✔️ ] Determine best approach for survey field type (Decision: It should exist as its own collection)
- [✔️ ] Create survey field type as a relation
- [✔️ ] Split place field type into region (required) and subregion (not required)

Notes: 
Survey could exist as its own collection which is then pointed to (as a relation) in the Assessment.NeedsData collection **OR** it could be created as a reusable component with the associated field types: id (string), year (string), quarter (string).

**Comment by jtfairbank** [comment]
Hey @ll-zerr great question!  We'll be building other things off of the Survey type as we port over other functionality, so I'd recommend making it it's own Collection to provide us more flexibility down the road. :)
